### ISSUE TITLE
RoadMap of Paddle2ONNX

### ISSUE THREAD

**Issue by jiangjiajun** [PaddlePaddle/Paddle2ONNX#254]
# Paddle2ONNX v0.8 (2021.08)
- [ ] Demo shows how to deploy Paddle model use C# through onnxruntime
- [ ] Quantize Model Support

# Paddle2ONNX v0.7 (2021.07)
- [ ] OpenVINO/OpenCV inference support different export method
- [ ] More OCR models add to Paddle2ONNX ci
- [ ] OP set version auto check and update
- [ ] ppyolo-tiny support deploy by opencv

# Paddle2ONNX v0.6 [Released](https://github.com/PaddlePaddle/Paddle2ONNX/releases/tag/v0.6)
- [x] PaddleDetection 2.0 support
- - [x] YOLOv3
- - [x] PPYOLO
- - [x] PPYOLOv2
- - [x] PPYOLO-Tiny
- - [x] TTFNet
- - [x] PAFNet
- - [x] FCOS
- - [x] SSD
- - [ ] FasterRCNN (Pending due to the condition block in RCNN models)

**Comment by jiangjiajun** [comment]
If you have any feature request, please update at this issue

**Comment by jiangjiajun** [comment]
# PaddleDetection 2.0 Support

We have release paddle2onnx v0.6 which support PaddleDetection 2.0, install with follow command
```
pip install paddle2onnx==0.6
```

**Comment by znsoftm** [comment]
Quantize Model Support ,  does it mean converting a quantized paddle model to  the quantized edition of onnx?

**Comment by jiangjiajun** [comment]
> Quantize Model Support , does it mean converting a quantized paddle model to the quantized edition of onnx?

Yes, but it's not sure for the feasibility now, still working on for it
